// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleServiceBooking.Auth.Data;

#nullable disable

namespace VehicleServiceBooking.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260718160842_RefactorUserRoleToGroupRoleModel")]
    partial class RefactorUserRoleToGroupRoleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c001"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default group for standard end users",
                            IsActive = true,
                            Name = "user",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c002"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrative group",
                            IsActive = true,
                            Name = "admin",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c003"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Super administrator group with full role coverage",
                            IsActive = true,
                            Name = "superadmin",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.GroupRole", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("GroupId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("GroupRoles");

                    b.HasData(
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c001"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d001"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c001"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d002"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c002"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d003"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c002"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d004"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c003"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d005"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c003"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d006"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c003"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d007"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GroupId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5c003"),
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5d008"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a002"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create appointments",
                            IsActive = true,
                            Name = "appointment:create",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a003"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View appointment availability and details",
                            IsActive = true,
                            Name = "appointment:view",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a004"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete appointments",
                            IsActive = true,
                            Name = "appointment:complete",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a005"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create orders",
                            IsActive = true,
                            Name = "order:create",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a006"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View orders",
                            IsActive = true,
                            Name = "order:view",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a007"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit orders",
                            IsActive = true,
                            Name = "order:edit",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a008"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cancel orders",
                            IsActive = true,
                            Name = "order:cancel",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a009"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete orders",
                            IsActive = true,
                            Name = "order:complete",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role for booking resource operations",
                            IsActive = true,
                            Name = "booking-admin",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default role for booking resource operations",
                            IsActive = true,
                            Name = "booking-user",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role for order resource operations",
                            IsActive = true,
                            Name = "order-admin",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default role for order resource operations",
                            IsActive = true,
                            Name = "order-user",
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a002"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b001"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a003"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b002"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a001"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a004"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b003"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a005"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b005"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a006"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b006"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a007"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b007"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a008"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b008"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a010"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a009"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b009"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a002"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b011"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a003"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b012"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a011"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a004"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b013"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a005"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b014"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a006"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b015"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a007"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b016"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a008"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b017"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a012"),
                            PermissionId = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5a009"),
                            CreatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("2d7b6113-2351-4b60-848f-8c3d28f5b018"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuthenticatorAppSecret")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailVerificationTokenHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAuthenticatorAppEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("LoginVerificationChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginVerificationChannel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("email_otp");

                    b.Property<int>("LoginVerificationCodeAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LoginVerificationCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginVerificationCodeHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ZaloUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.GroupRole", b =>
                {
                    b.HasOne("VehicleServiceBooking.Auth.Models.Group", "Group")
                        .WithMany("GroupRoles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceBooking.Auth.Models.Role", "Role")
                        .WithMany("GroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.RefreshToken", b =>
                {
                    b.HasOne("VehicleServiceBooking.Auth.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.RolePermission", b =>
                {
                    b.HasOne("VehicleServiceBooking.Auth.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceBooking.Auth.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.UserGroup", b =>
                {
                    b.HasOne("VehicleServiceBooking.Auth.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleServiceBooking.Auth.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Group", b =>
                {
                    b.Navigation("GroupRoles");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.Role", b =>
                {
                    b.Navigation("GroupRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("VehicleServiceBooking.Auth.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
