// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleServiceBooking.Infrastructure.Persistence;

#nullable disable

namespace VehicleServiceBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627190136_AddAvailabilityViews")]
    partial class AddAvailabilityViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.ServiceBayAvailableSlotsView", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceBayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TimeSlotId", "ServiceBayId")
                        .HasName("PK_ServiceBayAvailableSlots");

                    b.ToTable((string)null);

                    b.ToView("ServiceBayAvailableSlots", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.ServiceTypeAvailabilityView", b =>
                {
                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanFitService")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("RequiredSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceBayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ServiceTypeId", "TimeSlotId", "TechnicianId", "ServiceBayId")
                        .HasName("PK_ServiceTypeAvailability");

                    b.ToTable((string)null);

                    b.ToView("ServiceTypeAvailability", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.TechnicianAvailableSlotsView", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TimeSlotId", "TechnicianId")
                        .HasName("PK_TechnicianAvailableSlots");

                    b.ToTable((string)null);

                    b.ToView("TechnicianAvailableSlots", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Appointments");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealershipId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_AppointmentStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_AppointmentStatusLookup_Status_Unique");

                    b.ToTable("AppointmentStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7220),
                            Description = "Appointment is scheduled",
                            Name = "Booked",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7220)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7220),
                            Description = "Service is currently being performed",
                            Name = "In Progress",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7220)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7230),
                            Description = "Service has been completed",
                            Name = "Completed",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7230)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7230),
                            Description = "Appointment has been cancelled",
                            Name = "Cancelled",
                            Status = 4,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7230)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7240),
                            Description = "Some services completed, others rescheduled",
                            Name = "Partially Completed",
                            Status = 5,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 220, DateTimeKind.Utc).AddTicks(7240)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_BusinessHours");

                    b.HasIndex("DealershipId");

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Customers");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Dealership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Dealerships");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstimatedEndTimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstimatedStartTimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Services");

                    b.HasIndex("DealershipId");

                    b.HasIndex("EstimatedEndTimeSlotId");

                    b.HasIndex("EstimatedStartTimeSlotId");

                    b.HasIndex("ServiceBayId");

                    b.HasIndex("ServiceStatusId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("AppointmentId", "ServiceTypeId", "SequenceOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Service_Unique_AppointmentServiceTypeSequence");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceBays");

                    b.HasIndex("DealershipId");

                    b.ToTable("ServiceBays");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceStatusLookup_Status_Unique");

                    b.ToTable("ServiceStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(870),
                            Description = "Service scheduled but not started",
                            Name = "Pending",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(870)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(880),
                            Description = "Service is currently being performed",
                            Name = "In Progress",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(880)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(880),
                            Description = "Service has been completed successfully",
                            Name = "Completed",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(880)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(890),
                            Description = "Service was cancelled or declined",
                            Name = "Skipped",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(890)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(890),
                            Description = "Service moved to a different appointment",
                            Name = "Rescheduled",
                            Status = 4,
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 221, DateTimeKind.Utc).AddTicks(890)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceTypes");

                    b.ToTable("ServiceTypes", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceType_DurationMinutes_Range", "\"DurationMinutes\" >= 30 AND \"DurationMinutes\" <= 480");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Technicians");

                    b.HasIndex("DealershipId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TechnicianSchedules");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianSchedules");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TechnicianSkills");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TechnicianId", "ServiceTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_TechnicianSkill_Unique_TechnicianServiceType");

                    b.ToTable("TechnicianSkills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TimeSlots");

                    b.HasIndex("SequenceOrder")
                        .IsUnique()
                        .HasDatabaseName("UK_TimeSlot_SequenceOrder");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1060),
                            IsActive = true,
                            SequenceOrder = 1,
                            SlotEndTime = new TimeOnly(8, 30, 0),
                            SlotStartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1060)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1070),
                            IsActive = true,
                            SequenceOrder = 2,
                            SlotEndTime = new TimeOnly(9, 0, 0),
                            SlotStartTime = new TimeOnly(8, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1070)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1080),
                            IsActive = true,
                            SequenceOrder = 3,
                            SlotEndTime = new TimeOnly(9, 30, 0),
                            SlotStartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1080)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1080),
                            IsActive = true,
                            SequenceOrder = 4,
                            SlotEndTime = new TimeOnly(10, 0, 0),
                            SlotStartTime = new TimeOnly(9, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1080)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1090),
                            IsActive = true,
                            SequenceOrder = 5,
                            SlotEndTime = new TimeOnly(10, 30, 0),
                            SlotStartTime = new TimeOnly(10, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1090)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1100),
                            IsActive = true,
                            SequenceOrder = 6,
                            SlotEndTime = new TimeOnly(11, 0, 0),
                            SlotStartTime = new TimeOnly(10, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1100)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1100),
                            IsActive = true,
                            SequenceOrder = 7,
                            SlotEndTime = new TimeOnly(11, 30, 0),
                            SlotStartTime = new TimeOnly(11, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1100)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1110),
                            IsActive = true,
                            SequenceOrder = 8,
                            SlotEndTime = new TimeOnly(12, 0, 0),
                            SlotStartTime = new TimeOnly(11, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1110)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1110),
                            IsActive = true,
                            SequenceOrder = 9,
                            SlotEndTime = new TimeOnly(12, 30, 0),
                            SlotStartTime = new TimeOnly(12, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1110)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1120),
                            IsActive = true,
                            SequenceOrder = 10,
                            SlotEndTime = new TimeOnly(13, 0, 0),
                            SlotStartTime = new TimeOnly(12, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1120)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1130),
                            IsActive = true,
                            SequenceOrder = 11,
                            SlotEndTime = new TimeOnly(13, 30, 0),
                            SlotStartTime = new TimeOnly(13, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1130),
                            IsActive = true,
                            SequenceOrder = 12,
                            SlotEndTime = new TimeOnly(14, 0, 0),
                            SlotStartTime = new TimeOnly(13, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1130)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1140),
                            IsActive = true,
                            SequenceOrder = 13,
                            SlotEndTime = new TimeOnly(14, 30, 0),
                            SlotStartTime = new TimeOnly(14, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1140)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1140),
                            IsActive = true,
                            SequenceOrder = 14,
                            SlotEndTime = new TimeOnly(15, 0, 0),
                            SlotStartTime = new TimeOnly(14, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1140)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1150),
                            IsActive = true,
                            SequenceOrder = 15,
                            SlotEndTime = new TimeOnly(15, 30, 0),
                            SlotStartTime = new TimeOnly(15, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1150)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1160),
                            IsActive = true,
                            SequenceOrder = 16,
                            SlotEndTime = new TimeOnly(16, 0, 0),
                            SlotStartTime = new TimeOnly(15, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1160)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1160),
                            IsActive = true,
                            SequenceOrder = 17,
                            SlotEndTime = new TimeOnly(16, 30, 0),
                            SlotStartTime = new TimeOnly(16, 0, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1160)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1170),
                            IsActive = true,
                            SequenceOrder = 18,
                            SlotEndTime = new TimeOnly(17, 0, 0),
                            SlotStartTime = new TimeOnly(16, 30, 0),
                            UpdatedAt = new DateTime(2026, 6, 27, 19, 1, 36, 224, DateTimeKind.Utc).AddTicks(1170)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Vehicles");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_VIN_Length", "LENGTH(\"Vin\") = 17");

                            t.HasCheckConstraint("CK_Vehicle_Year_Range", "\"Year\" IS NULL OR (\"Year\" >= 1900 AND \"Year\" <= 2100)");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Customer");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Appointments")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Dealership");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_AppointmentStatus");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Vehicle");

                    b.Navigation("Customer");

                    b.Navigation("Dealership");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.BusinessHours", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("BusinessHours")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BusinessHours_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Service", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Services")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Service_Appointment");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Services")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_Dealership");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.TimeSlot", "EstimatedEndTimeSlot")
                        .WithMany("EstimatedEndServices")
                        .HasForeignKey("EstimatedEndTimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Service_TimeSlot_End");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.TimeSlot", "EstimatedStartTimeSlot")
                        .WithMany("EstimatedStartServices")
                        .HasForeignKey("EstimatedStartTimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Service_TimeSlot_Start");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceBay", "ServiceBay")
                        .WithMany("Services")
                        .HasForeignKey("ServiceBayId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Service_ServiceBay");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", "ServiceStatus")
                        .WithMany("Services")
                        .HasForeignKey("ServiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_ServiceStatus");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_ServiceType");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Services")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Service_Technician");

                    b.Navigation("Appointment");

                    b.Navigation("Dealership");

                    b.Navigation("EstimatedEndTimeSlot");

                    b.Navigation("EstimatedStartTimeSlot");

                    b.Navigation("ServiceBay");

                    b.Navigation("ServiceStatus");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("ServiceBays")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBay_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Technicians")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Technician_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSchedule", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Schedules")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSchedule_Technician");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSkill", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("TechnicianSkills")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSkill_ServiceType");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Skills")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSkill_Technician");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Dealership", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BusinessHours");

                    b.Navigation("ServiceBays");

                    b.Navigation("Services");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("TechnicianSkills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("EstimatedEndServices");

                    b.Navigation("EstimatedStartServices");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
