// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleServiceBooking.Infrastructure.Persistence;

#nullable disable

namespace VehicleServiceBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718060148_AddPaymentOrderAndTransactionSimplification")]
    partial class AddPaymentOrderAndTransactionSimplification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.ServiceBayAvailableSlotsView", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceBayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TimeSlotId", "ServiceBayId")
                        .HasName("PK_ServiceBayAvailableSlots");

                    b.ToTable((string)null);

                    b.ToView("ServiceBayAvailableSlots", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.ServiceTypeAvailabilityView", b =>
                {
                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CanFitService")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("RequiredSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceBayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ServiceTypeId", "TimeSlotId", "TechnicianId", "ServiceBayId")
                        .HasName("PK_ServiceTypeAvailability");

                    b.ToTable((string)null);

                    b.ToView("ServiceTypeAvailability", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Application.Models.ViewModels.TechnicianAvailableSlotsView", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("QueryDate")
                        .HasColumnType("date");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TimeSlotId", "TechnicianId")
                        .HasName("PK_TechnicianAvailableSlots");

                    b.ToTable((string)null);

                    b.ToView("TechnicianAvailableSlots", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Appointments");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DealershipId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_AppointmentStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_AppointmentStatusLookup_Status_Unique");

                    b.ToTable("AppointmentStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9780),
                            Description = "Appointment is scheduled",
                            IsActive = true,
                            Name = "Booked",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9780)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790),
                            Description = "Service is currently being performed",
                            IsActive = true,
                            Name = "In Progress",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790),
                            Description = "Service has been completed",
                            IsActive = true,
                            Name = "Completed",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790),
                            Description = "Appointment has been cancelled",
                            IsActive = true,
                            Name = "Cancelled",
                            Status = 4,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9790)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9800),
                            Description = "Some services completed, others rescheduled",
                            IsActive = true,
                            Name = "Partially Completed",
                            Status = 5,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 325, DateTimeKind.Utc).AddTicks(9800)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_BusinessHours");

                    b.HasIndex("DealershipId");

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.CurrencyLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_CurrencyLookups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CurrencyLookup_Code_Unique");

                    b.ToTable("CurrencyLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Code = "VND",
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(5010),
                            DecimalPlaces = 0,
                            IsActive = true,
                            Name = "Vietnamese Dong",
                            Symbol = "VND",
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(5010)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(5010),
                            DecimalPlaces = 2,
                            IsActive = true,
                            Name = "US Dollar",
                            Symbol = "USD",
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(5020)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Customers");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_AuthUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Dealership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Dealerships");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.IdempotencyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_IdempotencyRequests");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_IdempotencyRequest_ExpiresAt");

                    b.HasIndex("StatusId");

                    b.HasIndex("IdempotencyKey", "RequestPath")
                        .IsUnique()
                        .HasDatabaseName("IX_IdempotencyRequest_Key_Path_Unique");

                    b.ToTable("IdempotencyRequests");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.IdempotencyRequestStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_IdempotencyRequestStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_IdempotencyRequestStatusLookup_Status_Unique");

                    b.ToTable("IdempotencyRequestStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(3840),
                            Description = "Request processing started and not yet completed",
                            IsActive = true,
                            Name = "In Progress",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(3840)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(3840),
                            Description = "Request completed and response persisted for replay",
                            IsActive = true,
                            Name = "Completed",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(3840)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Orders");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Order_OrderCode_Unique");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.OrderAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_OrderAppointments");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderAppointment_Appointment_Unique");

                    b.HasIndex("OrderId", "AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderAppointment_Unique_Order_Appointment");

                    b.ToTable("OrderAppointments");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_PaymentOrders");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentOrder_OrderId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentOrder_TransactionId_Unique");

                    b.ToTable("PaymentOrders");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentProviderLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_PaymentProviderLookups");

                    b.HasIndex("Provider")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentProviderLookup_Provider_Unique");

                    b.ToTable("PaymentProviderLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9030),
                            Description = "Zalo Pay e-wallet and gateway",
                            IsActive = true,
                            Name = "Zalo Pay",
                            Provider = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9040),
                            Description = "Momo wallet payments",
                            IsActive = true,
                            Name = "Momo",
                            Provider = 2,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9040),
                            Description = "Apple Pay card tokenization gateway",
                            IsActive = true,
                            Name = "Apple Pay",
                            Provider = 3,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9060),
                            Description = "Visa card network",
                            IsActive = true,
                            Name = "Visa",
                            Provider = 4,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9060)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9060),
                            Description = "MasterCard card network",
                            IsActive = true,
                            Name = "Master Card",
                            Provider = 5,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9060)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9070),
                            Description = "VNPay online payment gateway",
                            IsActive = true,
                            Name = "VNPay",
                            Provider = 6,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9070)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9070),
                            Description = "Domestic ATM transfer",
                            IsActive = true,
                            Name = "ATM Transfer",
                            Provider = 7,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9070)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9080),
                            Description = "Internal system wallet balance",
                            IsActive = true,
                            Name = "Internal Wallet",
                            Provider = 8,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9080)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("FromAccount")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToAccount")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("TransactionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_PaymentTransactions");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTransaction_TransactionCode_Unique");

                    b.ToTable("PaymentTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransaction_Amount_NonNegative", "\"Amount\" >= 0");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentTransactionStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_PaymentTransactionStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTransactionStatusLookup_Status_Unique");

                    b.ToTable("PaymentTransactionStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9430),
                            Description = "Transaction is created and waiting for processing",
                            IsActive = true,
                            Name = "Pending",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9430)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9430),
                            Description = "Transaction is being processed",
                            IsActive = true,
                            Name = "In Progress",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9440)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9440),
                            Description = "Transaction has been completed successfully",
                            IsActive = true,
                            Name = "Completed",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 327, DateTimeKind.Utc).AddTicks(9440)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedEndSlotSequenceExclusive")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EstimatedEndTimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedStartSlotSequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EstimatedStartTimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Services");

                    b.HasIndex("EstimatedEndTimeSlotId");

                    b.HasIndex("EstimatedStartTimeSlotId");

                    b.HasIndex("ServiceStatusId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("DealershipId", "BookingDate")
                        .HasDatabaseName("IX_Service_Dealership_BookingDate");

                    b.HasIndex("ServiceBayId", "BookingDate")
                        .HasDatabaseName("IX_Service_ServiceBay_BookingDate");

                    b.HasIndex("TechnicianId", "BookingDate")
                        .HasDatabaseName("IX_Service_Technician_BookingDate");

                    b.HasIndex("AppointmentId", "ServiceTypeId", "SequenceOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Service_Unique_AppointmentServiceTypeSequence");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceBays");

                    b.HasIndex("DealershipId");

                    b.ToTable("ServiceBays");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceStatusLookups");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceStatusLookup_Status_Unique");

                    b.ToTable("ServiceStatusLookups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5580),
                            Description = "Service scheduled but not started",
                            IsActive = true,
                            Name = "Pending",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5580)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590),
                            Description = "Service is currently being performed",
                            IsActive = true,
                            Name = "In Progress",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590),
                            Description = "Service has been completed successfully",
                            IsActive = true,
                            Name = "Completed",
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590),
                            Description = "Service was cancelled or declined",
                            IsActive = true,
                            Name = "Skipped",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5590)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5600),
                            Description = "Service moved to a different appointment",
                            IsActive = true,
                            Name = "Rescheduled",
                            Status = 4,
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 326, DateTimeKind.Utc).AddTicks(5600)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceTypes");

                    b.ToTable("ServiceTypes", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceType_DurationMinutes_Range", "\"DurationMinutes\" >= 30 AND \"DurationMinutes\" <= 480");

                            t.HasCheckConstraint("CK_ServiceType_Price_NonNegative", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceTypeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceTypeOrders");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("OrderId", "ServiceTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceTypeOrder_Unique_Order_ServiceType");

                    b.ToTable("ServiceTypeOrders", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceTypeOrder_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceTypePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ServiceTypePrices");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ServiceTypeId", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("IX_ServiceTypePrice_Unique_ServiceType_Currency");

                    b.ToTable("ServiceTypePrices", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceTypePrice_Price_NonNegative", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Technicians");

                    b.HasIndex("DealershipId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TechnicianSchedules");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianSchedules");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TechnicianSkills");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TechnicianId", "ServiceTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_TechnicianSkill_Unique_TechnicianServiceType");

                    b.ToTable("TechnicianSkills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_TimeSlots");

                    b.HasIndex("SequenceOrder")
                        .IsUnique()
                        .HasDatabaseName("UK_TimeSlot_SequenceOrder");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(660),
                            IsActive = true,
                            SequenceOrder = 1,
                            SlotEndTime = new TimeOnly(8, 30, 0),
                            SlotStartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(660)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(670),
                            IsActive = true,
                            SequenceOrder = 2,
                            SlotEndTime = new TimeOnly(9, 0, 0),
                            SlotStartTime = new TimeOnly(8, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(670)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(680),
                            IsActive = true,
                            SequenceOrder = 3,
                            SlotEndTime = new TimeOnly(9, 30, 0),
                            SlotStartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(680)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(690),
                            IsActive = true,
                            SequenceOrder = 4,
                            SlotEndTime = new TimeOnly(10, 0, 0),
                            SlotStartTime = new TimeOnly(9, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(690)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(690),
                            IsActive = true,
                            SequenceOrder = 5,
                            SlotEndTime = new TimeOnly(10, 30, 0),
                            SlotStartTime = new TimeOnly(10, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(690)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(700),
                            IsActive = true,
                            SequenceOrder = 6,
                            SlotEndTime = new TimeOnly(11, 0, 0),
                            SlotStartTime = new TimeOnly(10, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(700)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(700),
                            IsActive = true,
                            SequenceOrder = 7,
                            SlotEndTime = new TimeOnly(11, 30, 0),
                            SlotStartTime = new TimeOnly(11, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(700)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(710),
                            IsActive = true,
                            SequenceOrder = 8,
                            SlotEndTime = new TimeOnly(12, 0, 0),
                            SlotStartTime = new TimeOnly(11, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(710)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(720),
                            IsActive = true,
                            SequenceOrder = 9,
                            SlotEndTime = new TimeOnly(12, 30, 0),
                            SlotStartTime = new TimeOnly(12, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(720)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(720),
                            IsActive = true,
                            SequenceOrder = 10,
                            SlotEndTime = new TimeOnly(13, 0, 0),
                            SlotStartTime = new TimeOnly(12, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(720)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(730),
                            IsActive = true,
                            SequenceOrder = 11,
                            SlotEndTime = new TimeOnly(13, 30, 0),
                            SlotStartTime = new TimeOnly(13, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(730)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(740),
                            IsActive = true,
                            SequenceOrder = 12,
                            SlotEndTime = new TimeOnly(14, 0, 0),
                            SlotStartTime = new TimeOnly(13, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(740)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(740),
                            IsActive = true,
                            SequenceOrder = 13,
                            SlotEndTime = new TimeOnly(14, 30, 0),
                            SlotStartTime = new TimeOnly(14, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(740)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(750),
                            IsActive = true,
                            SequenceOrder = 14,
                            SlotEndTime = new TimeOnly(15, 0, 0),
                            SlotStartTime = new TimeOnly(14, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(750)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(760),
                            IsActive = true,
                            SequenceOrder = 15,
                            SlotEndTime = new TimeOnly(15, 30, 0),
                            SlotStartTime = new TimeOnly(15, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(760)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(760),
                            IsActive = true,
                            SequenceOrder = 16,
                            SlotEndTime = new TimeOnly(16, 0, 0),
                            SlotStartTime = new TimeOnly(15, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(760)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(770),
                            IsActive = true,
                            SequenceOrder = 17,
                            SlotEndTime = new TimeOnly(16, 30, 0),
                            SlotStartTime = new TimeOnly(16, 0, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(770)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(770),
                            IsActive = true,
                            SequenceOrder = 18,
                            SlotEndTime = new TimeOnly(17, 0, 0),
                            SlotStartTime = new TimeOnly(16, 30, 0),
                            UpdatedAt = new DateTime(2026, 7, 18, 6, 1, 48, 331, DateTimeKind.Utc).AddTicks(770)
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Vehicles");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_VIN_Length", "LENGTH(\"Vin\") = 17");

                            t.HasCheckConstraint("CK_Vehicle_Year_Range", "\"Year\" IS NULL OR (\"Year\" >= 1900 AND \"Year\" <= 2100)");
                        });
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Customer");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Appointments")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Dealership");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_AppointmentStatus");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Vehicle");

                    b.Navigation("Customer");

                    b.Navigation("Dealership");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.BusinessHours", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("BusinessHours")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BusinessHours_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.IdempotencyRequest", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.IdempotencyRequestStatusLookup", "Status")
                        .WithMany("IdempotencyRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_IdempotencyRequest_StatusLookup");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.OrderAppointment", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Appointment", "Appointment")
                        .WithOne("OrderAppointment")
                        .HasForeignKey("VehicleServiceBooking.Domain.Entities.OrderAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderAppointment_Appointment");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Order", "Order")
                        .WithMany("OrderAppointments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderAppointment_Order");

                    b.Navigation("Appointment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Order", "Order")
                        .WithOne("PaymentOrder")
                        .HasForeignKey("VehicleServiceBooking.Domain.Entities.PaymentOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentOrder_Order");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithOne("PaymentOrder")
                        .HasForeignKey("VehicleServiceBooking.Domain.Entities.PaymentOrder", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentOrder_PaymentTransaction");

                    b.Navigation("Order");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.CurrencyLookup", "Currency")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransaction_Currency");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.PaymentTransactionStatusLookup", "Status")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransaction_StatusLookup");

                    b.Navigation("Currency");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Service", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Services")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Service_Appointment");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Services")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_Dealership");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.TimeSlot", "EstimatedEndTimeSlot")
                        .WithMany("EstimatedEndServices")
                        .HasForeignKey("EstimatedEndTimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Service_TimeSlot_End");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.TimeSlot", "EstimatedStartTimeSlot")
                        .WithMany("EstimatedStartServices")
                        .HasForeignKey("EstimatedStartTimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Service_TimeSlot_Start");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceBay", "ServiceBay")
                        .WithMany("Services")
                        .HasForeignKey("ServiceBayId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Service_ServiceBay");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", "ServiceStatus")
                        .WithMany("Services")
                        .HasForeignKey("ServiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_ServiceStatus");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Service_ServiceType");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Services")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Service_Technician");

                    b.Navigation("Appointment");

                    b.Navigation("Dealership");

                    b.Navigation("EstimatedEndTimeSlot");

                    b.Navigation("EstimatedStartTimeSlot");

                    b.Navigation("ServiceBay");

                    b.Navigation("ServiceStatus");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("ServiceBays")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceBay_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceTypeOrder", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Order", "Order")
                        .WithMany("ServiceTypeOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTypeOrder_Order");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceTypeOrders")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTypeOrder_ServiceType");

                    b.Navigation("Order");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceTypePrice", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.CurrencyLookup", "Currency")
                        .WithMany("ServiceTypePrices")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTypePrice_Currency");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceTypePrices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTypePrice_ServiceType");

                    b.Navigation("Currency");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Dealership", "Dealership")
                        .WithMany("Technicians")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Technician_Dealership");

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSchedule", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Schedules")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSchedule_Technician");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TechnicianSkill", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("TechnicianSkills")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSkill_ServiceType");

                    b.HasOne("VehicleServiceBooking.Domain.Entities.Technician", "Technician")
                        .WithMany("Skills")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TechnicianSkill_Technician");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleServiceBooking.Domain.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("OrderAppointment");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.AppointmentStatusLookup", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.CurrencyLookup", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("ServiceTypePrices");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Dealership", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BusinessHours");

                    b.Navigation("ServiceBays");

                    b.Navigation("Services");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.IdempotencyRequestStatusLookup", b =>
                {
                    b.Navigation("IdempotencyRequests");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderAppointments");

                    b.Navigation("PaymentOrder");

                    b.Navigation("ServiceTypeOrders");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Navigation("PaymentOrder");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.PaymentTransactionStatusLookup", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceBay", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceStatusLookup", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("ServiceTypeOrders");

                    b.Navigation("ServiceTypePrices");

                    b.Navigation("Services");

                    b.Navigation("TechnicianSkills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Technician", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("EstimatedEndServices");

                    b.Navigation("EstimatedStartServices");
                });

            modelBuilder.Entity("VehicleServiceBooking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
